[package]
name = "wrust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "weft"
path = "src/main.rs"

[dependencies]
pest = "2.7"
pest_derive = "2.7"
thiserror = "1.0"
petgraph = "0.6"
clap = { version = "4.5", features = ["derive"] }
minifb = "0.27"
